<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRnnP7xx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRnnP7xx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRnnP7xx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRnnP7xx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRnnP7xx\App_KernelDevDebugContainer([
    'container.build_hash' => 'RnnP7xx',
    'container.build_id' => 'a4b52998',
    'container.build_time' => 1641466489,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRnnP7xx');
